### ISSUE TITLE
Add 2 Participatory Space Roles : Committee & Service

### ISSUE THREAD

**Issue by moustachu** [OpenSourcePolitics/decidim-questions#3]
## Object : 
Add new roles to participatory space to enable a workflow for answer on `Questions` : 
- the `admin` and `moderator` roles are unchanged
- the **new** `committee` role should group users who will validate questions and official answer berore moving them in the workflow
- the **new** `service` role should group users who will provide official answer to validated questions 

## Tasks 

- [x] Add "Committee" & "Service" to the Participatory Space Roles list
- [x] **(To be validated)** _Add a new participatory space setting to enable to Committee/Service roles_
- [x] Add a new component setting on `Questions` to enable to Committee/Service workflow
- [x] Each new roles should be able to **only** access the `Questions` components in a participatory space
- [x] Add tests 
- [ ] Add documentation

**Comment by moustachu** [comment]
**--> referenced in commit https://github.com/OpenSourcePolitics/decidim-questions/commit/c535ad6eed74144bd18a6efd386d36cba4ac190b**

**Comment by lu-hamani** [comment]
> ## Tasks
> * [ ]  **(To be validated)** _Add a new participatory space setting to enable to Committee/Service roles_

@moustachu 
Do you consider this specific task as done since the setting is present in the question component ? Why do you think it should be set at the participatory space level rather than component or process ?
